export enum MESSAGE {
  SENDMESSAGE = "SENDMESSAGE",
  SENDCHANNELMESSAGE = "SENDCHANNELMESSAGE",
}

export enum CHANNEL {
  GETCHANNEL = "GETCHANNEL",
  NEWCHANNELADD = "NEWCHANNELADD",
}

export enum FILE {
  FILEUPLOAD = "FILEUPLOAD",
}

export enum USERS {
  GETUSERS = "GETUSERS",
  GETUSERBYID = "GETUSERBYID",
}

export enum COMMON {
  ADDTOFAVOURITE = "ADDTOFAVOURITE",
  MESSAGEREAD = "MESSAGEREAD",
  TYPING = "TYPING",

}

export enum CHAT {
  GETCHATBYUSERID='GETCHATBYUSERID',
  SERACHMESSAGE='SERACHMESSAGE',
  GETCHATLIST = "GETCHATLIST",
}

export enum CONNECTION {
  CONNECTIONSTATUS = "CONNECTIONSTATUS",
}



